
SELECT EMP_NAME, NVL(DEPT_TITLE, '부서없음') AS DEPT_TITLE, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID) 
WHERE NVL(DEPT_TITLE, '부서없음') = '총무부' ;

-- 주의 !) 
-- 1) JAVA에서 TITLE을 지정해놨기 떄문에 함수로 인해 이상해진 TITLE은 별칭 재지정
-- 2) JAVA에서 조건을 가져올때, '' 없다는거 인지하기.

SELECT DEPT_TITLE
FROM DEPARTMENT ;



SELECT EMP_NAME, JOB_NAME, SALARY , SALARY *12 AS ANNUAL_INCOME
FROM EMPLOYEE 
LEFT JOIN JOB USING(JOB_CODE)
WHERE JOB_NAME = '부장' AND SALARY > 1000000;


SELECT EMP_NAME, TO_CHAR(HIRE_DATE,'yyyy"년 "mm"월 "dd"일"') HIRE_DATE,
DECODE(SUBSTR(EMP_NO, 8, 1) ,'1', 'M','2','F') AS GENDER
FROM EMPLOYEE 
WHERE TO_CHAR(HIRE_DATE,'yyyy-mm-dd') < '2000-01-02';


-- 선생님 풀이
SELECT EMP_NAME 이름, TO_CHAR(HIRE_DATE,'yyyy"년 "mm"월 "dd"일"') 입사일,
DECODE(SUBSTR(EMP_NO, 8, 1) ,'1', 'M','2','F') 성별
FROM EMPLOYEE 
WHERE HIRE_DATE < TO_DATE('2000-01-01');